# Generated by Django 5.1.3 on 2025-02-10 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cargaHoraria', models.IntegerField(verbose_name='Carga Horária')),
                ('presencial', models.BooleanField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.departamento')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.modalidade')),
            ],
        ),
    ]
